# Generated by Django 4.0.4 on 2022-06-15 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('lastTime', models.CharField(max_length=25)),
                ('buyingPrice', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('macd', models.FloatField()),
                ('macdTriggered', models.FloatField()),
                ('parabolicSAR', models.FloatField()),
                ('ema', models.FloatField()),
                ('sma', models.FloatField()),
                ('atr', models.FloatField()),
                ('rsi', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
