# Generated by Django 4.0.4 on 2022-06-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=10)),
                ('lastTime', models.CharField(max_length=25)),
                ('buyingPrice', models.FloatField()),
            ],
        ),
    ]
