# Generated by Django 4.0.4 on 2022-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0004_calendar_random_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='realizedPL',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='random',
            name='realizedPL',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='realizedPL',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='realizedPL',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
