# Generated by Django 4.0.4 on 2022-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading_B', '0006_delete_calendar_delete_random_delete_sd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('factor', models.FloatField()),
                ('longShort', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('buyingPrice', models.FloatField()),
                ('time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('buyingPrice', models.FloatField()),
                ('time', models.DateField(auto_now=True)),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('lastTime', models.CharField(max_length=25)),
                ('buyingPrice', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('macd', models.FloatField()),
                ('macdTriggered', models.FloatField()),
                ('parabolicSAR', models.FloatField()),
                ('ema', models.FloatField()),
                ('sma', models.FloatField()),
                ('atr', models.FloatField()),
                ('rsi', models.FloatField()),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('volatility', models.CharField(max_length=10)),
                ('time', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('buyingPrice', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
