# Generated by Django 4.0.4 on 2022-07-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='atr',
            new_name='atr14',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='ema',
            new_name='ema200',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='parabolicSAR',
            new_name='parabolicSAR14',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='rsi',
            new_name='sma20',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='sma',
            new_name='sma50',
        ),
    ]
