# Generated by Django 4.0.4 on 2022-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0008_rename_atr_signal_atr14_rename_ema_signal_ema200_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
