# Generated by Django 4.0.4 on 2022-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0010_alter_balance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
