# Generated by Django 4.0.4 on 2022-07-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0014_alter_calendar_time_alter_random_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
