# Generated by Django 4.0.4 on 2022-07-18 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading_B', '0015_delete_balance_delete_calendar_delete_random_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('factor', models.FloatField()),
                ('longShort', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('buyingPrice', models.FloatField()),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('typ', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('buyingPrice', models.FloatField()),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('sellingPrice', models.FloatField()),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('typ', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('lastTime', models.CharField(max_length=25)),
                ('buyingPrice', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('macd', models.FloatField()),
                ('macdTriggered', models.FloatField()),
                ('parabolicSAR14', models.FloatField()),
                ('ema200', models.FloatField()),
                ('sma20', models.FloatField()),
                ('sma50', models.FloatField()),
                ('atr14', models.FloatField()),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('typ', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=10)),
                ('volatility', models.CharField(max_length=10)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=10)),
                ('realizedPL', models.FloatField(blank=True, default=None, null=True)),
                ('buyingPrice', models.FloatField()),
                ('typ', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
