# Generated by Django 4.0.4 on 2022-07-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_B', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random',
            name='sellingPrice',
        ),
    ]
